apiVersion: v1
kind: PersistentVolume
metadata:
  name: 2-my-pv
spec:
  storageClassName: ""    # Empty string must be explicitly set otherwise default StorageClass will be set
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
