apiVersion: v1
kind: Service
metadata:
  name: pgadmin-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: pgadmin
  ports:
  - protocol: TCP
    port: 9090       # Service port
    targetPort: 80 # Port exposed by the pgAdmin container
