apiVersion: v1
kind: Service
metadata:
  name: pgadmin-node-port-service
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
  - protocol: TCP
    port: 80  
    targetPort: 80 # Port exposed by the pgAdmin container
    nodePort: 30080 # 30000-32767 Range -30000-32767 Range -30000-32767 Range -Port accessible on the node

