apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-second-pod
  template:
    metadata:
      labels:
        app: my-second-pod
        env: dsoc3
        "can-it-be-anything": "yes"
    spec:
      containers:
      - name: my-second-pod-container
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: host-storage
          mountPath: /logs
      volumes:
      - name: host-storage
        hostPath:
          path: /var/log/nginx
          type: DirectoryOrCreate

